#!/usr/bin/env bash
#
# doctor.sh — verify this store is linked, in sync, and secret-free.
#
set -uo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PI_SRC="$REPO_DIR/pi-agent"
PI_DST="${PI_CODING_AGENT_DIR:-$HOME/.pi/agent}"
STATE="$PI_DST/.pi-setup-state.json"
SKILLS_DST="${AGENTS_SKILLS_DIR:-$HOME/.agents/skills}"

problems=0
notes=0
ok() { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn() {
  printf '  \033[33m!\033[0m %s\n' "$1"
  notes=$((notes + 1))
}
bad() {
  printf '  \033[31m✗\033[0m %s\n' "$1"
  problems=$((problems + 1))
}

echo "==> Repo"
if [ -d "$REPO_DIR/.git" ]; then
  ok "git repository: $(git -C "$REPO_DIR" rev-parse --short HEAD 2>/dev/null || echo 'no commits yet')"
  remote="$(git -C "$REPO_DIR" remote get-url origin 2>/dev/null || true)"
  [ -n "$remote" ] && ok "remote: $remote" || warn "no 'origin' remote configured"
  if [ -n "$(git -C "$REPO_DIR" status --short)" ]; then
    warn "uncommitted changes:"
    git -C "$REPO_DIR" status --short | sed 's/^/      /'
  else
    ok "working tree clean"
  fi
else
  bad "not a git repository"
fi

LIB="$REPO_DIR/scripts/lib.sh"
if [ ! -f "$LIB" ]; then
  bad "scripts/lib.sh missing (it defines PI_DIRS/PI_FILES)"
  exit 1
fi
# shellcheck source=scripts/lib.sh
. "$LIB"

# One severity rule, decided once, used by every Trellis check below:
#
#   bad  when the fix is available and was not applied,
#   warn when the fix is not available on this machine.
#
# `.pi/` and `.agents/` are gitignored and regenerated by
# scripts/install-trellis.sh, which needs the Trellis CLI. So a missing surface
# on a machine that has the CLI is a real problem the user can fix with
# ./setup.sh; without the CLI it is an environment choice, not a defect.
if command -v trellis >/dev/null 2>&1; then
  trellis_cli=1
else
  trellis_cli=0
fi

echo "==> Settings  ($PI_DST/settings.json)"
if [ -L "$PI_DST/settings.json" ]; then
  bad "settings.json is a symlink; it should be generated (run ./setup.sh)"
elif [ -f "$PI_DST/settings.json" ]; then
  if node "$REPO_DIR/scripts/render-settings.mjs" "$REPO_DIR" "$PI_DST/settings.json" "$STATE" --check 2>&1 | sed 's/^/      /'; then
    ok "settings.json matches core + enabled optionals"
  else
    bad "settings.json has drifted from the repo"
  fi
else
  bad "settings.json missing (run ./setup.sh)"
fi

echo "==> Optional bundles"
if command -v node >/dev/null 2>&1 && [ -d "$REPO_DIR/optional" ]; then
  cur="$([ -f "$STATE" ] && node -e 'console.log((JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).optionals||[]).join("\n"))' "$STATE" || true)"
  any=0
  for m in "$REPO_DIR"/optional/*/manifest.json; do
    [ -e "$m" ] || continue
    name="$(basename "$(dirname "$m")")"
    case "$name" in _*) continue ;; esac
    any=1
    if printf '%s\n' "$cur" | grep -qx "$name"; then
      ok "$name (enabled)"
    else printf '  \033[2m·\033[0m %s (available)\n' "$name"; fi
  done
  [ "$any" = 1 ] || warn "no optional bundles defined"
else
  warn "node unavailable or optional/ missing"
fi

echo "==> MCP server  ($MCP_CFG)"
# MCP_CFG follows pi-mcp-adapter's hardcoded homedir path rather than the XDG
# standard (see scripts/lib.sh). Say so out loud when the two disagree, otherwise
# the path printed above looks like a bug on an XDG machine.
if [ -n "${XDG_CONFIG_HOME:-}" ] && [ "${XDG_CONFIG_HOME%/}" != "${HOME%/}/.config" ]; then
  warn "XDG_CONFIG_HOME=$XDG_CONFIG_HOME is set, but pi-mcp-adapter ignores it; the registration is at $MCP_CFG"
fi
if command -v codebase-memory-mcp >/dev/null 2>&1; then
  ok "codebase-memory-mcp: $(command -v codebase-memory-mcp)"
  has_cbm=1
else
  warn "codebase-memory-mcp not on PATH (run ./setup.sh, or --skip-mcp to opt out)"
  has_cbm=0
fi
if [ -f "$MCP_CFG" ]; then
  if ! command -v node >/dev/null 2>&1; then
    warn "cannot verify $MCP_CFG — node unavailable"
  elif out="$(node "$REPO_DIR/scripts/register-mcp-server.mjs" "$MCP_CFG" codebase-memory-mcp codebase-memory-mcp --check 2>&1)"; then
    ok "codebase-memory-mcp registered in $MCP_CFG"
  else
    printf '%s\n' "$out" | sed 's/^/      /'
    bad "registration in $MCP_CFG does not match (run ./setup.sh)"
  fi
elif [ "$has_cbm" = 1 ]; then
  bad "codebase-memory-mcp is installed but $MCP_CFG is missing (run ./setup.sh)"
fi

echo "==> Symlinked resources  ($PI_DST)"
found=0
for name in "${PI_FILES[@]}" "${PI_DIRS[@]}"; do
  src="$PI_SRC/$name"
  dst="$PI_DST/$name"
  [ -e "$src" ] || continue
  found=1
  if [ -L "$dst" ] && [ "$(readlink -f "$dst")" = "$(readlink -f "$src")" ]; then
    ok "$name -> repo"
  elif [ -L "$dst" ]; then
    bad "$name -> $(readlink "$dst")  (points elsewhere)"
  elif [ -e "$dst" ]; then
    warn "$name exists but is not linked (run ./setup.sh)"
  else
    warn "$name not linked (run ./setup.sh)"
  fi
done
[ "$found" = 1 ] || printf '  \033[2m·\033[0m none in repo yet (AGENTS.md, i-have-adhd.json, themes/, prompts/, tools/, skills/, agents/, extensions/)\n'

echo "==> Trellis adapters  ($REPO_DIR)"
# The surfaces `scripts/install-trellis.sh` generates. They are gitignored, so a
# fresh clone has none of them and only `./setup.sh` puts them back: `trellis
# update` reads their absence as an intentional deletion and exits "Already up to
# date". Severity follows the rule decided above.
if [ "$trellis_cli" = 1 ]; then
  ok "trellis CLI: $(command -v trellis)"
else
  warn "trellis CLI not on PATH; the .pi/ adapters cannot be generated (install: npm install -g @mindfoldhq/trellis)"
fi

# Enumerated because their names are a contract: `pi-subagents` discovers these
# roles from .pi/agents/ and the bridge extension dispatches to them. Prompts and
# skills are discovered instead — those file names are upstream's to change.
missing_trellis=()
[ -f "$REPO_DIR/.pi/settings.json" ] || missing_trellis+=(".pi/settings.json")
[ -f "$REPO_DIR/.pi/extensions/trellis/index.ts" ] || missing_trellis+=(".pi/extensions/trellis/index.ts")
for role in trellis-implement trellis-check trellis-research; do
  [ -f "$REPO_DIR/.pi/agents/$role.md" ] || missing_trellis+=(".pi/agents/$role.md")
done
compgen -G "$REPO_DIR/.pi/prompts/*.md" >/dev/null || missing_trellis+=(".pi/prompts/*.md")
compgen -G "$REPO_DIR/.agents/skills/trellis-*/SKILL.md" >/dev/null || missing_trellis+=(".agents/skills/trellis-*/SKILL.md")

if [ ${#missing_trellis[@]} -eq 0 ]; then
  ok ".pi/ adapters and .agents/skills/trellis-* present"
elif [ "$trellis_cli" = 1 ]; then
  bad "${#missing_trellis[@]} Trellis surface(s) missing — run ./setup.sh:"
  for p in "${missing_trellis[@]}"; do printf '      %s\n' "$p"; done
else
  warn "${#missing_trellis[@]} Trellis surface(s) missing, and the trellis CLI is unavailable:"
  for p in "${missing_trellis[@]}"; do printf '      %s\n' "$p"; done
fi

# Tracked, and rewritten by `trellis init` — which drops the `AGENTS.md` hash
# entry and would silently end `trellis update`'s management of it. Compared
# against HEAD rather than the index so a staged rewrite is still reported.
hashes_file=".trellis/.template-hashes.json"
if [ ! -f "$REPO_DIR/$hashes_file" ]; then
  bad "$hashes_file is missing (it is tracked; restore it with git)"
elif ! git -C "$REPO_DIR" rev-parse --git-dir >/dev/null 2>&1; then
  # `rev-parse --git-dir` rather than `[ -d .git ]`: a linked worktree has a
  # `.git` **file**, so the directory test would silently skip this check there.
  warn "not a git repository; cannot check $hashes_file against the committed copy"
elif ! git -C "$REPO_DIR" rev-parse --verify -q HEAD >/dev/null 2>&1; then
  warn "no commits yet; cannot check $hashes_file against a committed copy"
elif git -C "$REPO_DIR" diff --quiet HEAD -- "$hashes_file" 2>/dev/null; then
  ok "$hashes_file matches the committed copy"
else
  bad "$hashes_file differs from the committed copy"
  printf '      ./setup.sh reverts the next rewrite; commit or discard this one by hand\n'
fi

echo "==> Trellis subagent bridge"
bridge_src="$PI_SRC/extensions/trellis-subagents-bridge/index.ts"
if [ ! -f "$bridge_src" ]; then
  bad "pi-agent/extensions/trellis-subagents-bridge/index.ts missing"
elif [ ! -f "$PI_DST/extensions/trellis-subagents-bridge/index.ts" ]; then
  bad "bridge not reachable via $PI_DST/extensions (run ./setup.sh)"
else
  ok "bridge extension linked"
fi
# pi-subagents discovers project role agents from the project config agents dir.
# Assert the discovery INPUT rather than the tool's own listing: subagent({"action":"list"})
# is model-facing and cannot be called from bash.
pi_agents="$REPO_DIR/.pi/agents"
if [ ! -d "$pi_agents" ]; then
  if [ "$trellis_cli" = 1 ]; then
    bad ".pi/agents absent — run ./setup.sh to generate the Trellis adapters"
  else
    warn ".pi/agents absent and the trellis CLI is not on PATH; install it and run ./setup.sh"
  fi
else
  missing_agents=()
  for role in trellis-implement trellis-check trellis-research; do
    [ -f "$pi_agents/$role.md" ] || missing_agents+=("$role")
  done
  if [ ${#missing_agents[@]} -gt 0 ]; then
    bad "pi-subagents cannot discover role agent(s): ${missing_agents[*]}"
  else
    ok "pi-subagents discovery input present (3 role agents)"
  fi
fi

# Shipped dispatch tools. The bridge deactivates them by name, so a `trellis
# update` that renames one or registers another would silently end the
# deactivation. Compare the names the generated extension registers against the
# names the bridge declares. Offline, and no `pi` invocation: this must stay
# meaningful on a fresh clone.
#
# Every "cannot verify" path below fails or warns. A check that degrades to `ok`
# when it stops being able to see is worse than no check at all.
trellis_ext="$REPO_DIR/.pi/extensions/trellis/index.ts"
bridge_file="pi-agent/extensions/trellis-subagents-bridge/index.ts"
if [ ! -f "$trellis_ext" ]; then
  # Not a note either way: with the generated extension absent, the SHIPPED_TOOLS
  # comparison below cannot read its input, and a section that reports `ok` after
  # it stopped being able to see is worse than no section at all.
  if [ "$trellis_cli" = 1 ]; then
    bad ".pi/extensions/trellis/index.ts absent — run ./setup.sh; SHIPPED_TOOLS cannot be verified without it"
  else
    warn ".pi/extensions/trellis/index.ts absent and the trellis CLI is not on PATH; install it and run ./setup.sh"
  fi
elif [ ! -f "$bridge_src" ]; then
  : # the missing bridge was already reported above
elif [ ! -r "$trellis_ext" ]; then
  bad "cannot read .pi/extensions/trellis/index.ts; the bridge's SHIPPED_TOOLS list cannot be verified"
elif ! grep -q "SHIPPED_TOOLS" "$bridge_src" 2>/dev/null; then
  bad "the bridge no longer declares SHIPPED_TOOLS; doctor cannot verify which tools it deactivates"
else
  ext_names="$(grep -oE 'name: "[a-z_]+"' "$trellis_ext" 2>/dev/null | sed -E 's/.*"(.*)"/\1/' | sort -u)"
  # Read the declared list off its declaration line, not a bare quoted-string
  # match anywhere in the file: a name mentioned in the tool_call guard is not a
  # name the bridge deactivates.
  declared_line="$(grep 'SHIPPED_TOOLS' "$bridge_src" 2>/dev/null | grep -v '//' | head -n 1)"
  declared="$(printf '%s\n' "$declared_line" | grep -oE '"[a-z_]+"' | tr -d '"' | sort -u)"
  if [ -z "$declared" ]; then
    bad "read no tool name from the SHIPPED_TOOLS declaration in $bridge_file (empty or reformatted?)"
  elif [ -z "$ext_names" ]; then
    if grep -q "registerTool" "$trellis_ext" 2>/dev/null; then
      bad "the generated extension registers tool(s) but no name could be extracted (formatting drift?); the bridge's SHIPPED_TOOLS list can no longer be verified"
    else
      warn "the generated extension registers no dispatch tool; nothing for the bridge to deactivate"
    fi
  else
    unknown_tools=()
    while IFS= read -r t; do
      [ -n "$t" ] || continue
      printf '%s\n' "$declared" | grep -qxF "$t" || unknown_tools+=("$t")
    done <<<"$ext_names"
    if [ ${#unknown_tools[@]} -gt 0 ]; then
      bad "generated extension registers tool(s) the bridge does not deactivate:"
      for t in "${unknown_tools[@]}"; do printf '      %s\n' "$t"; done
      printf '      add each to SHIPPED_TOOLS in %s\n' "$bridge_file"
    else
      n_ext="$(printf '%s\n' "$ext_names" | grep -c .)"
      ok "shipped dispatch tool(s) covered by the bridge: $n_ext"
    fi
  fi

  # Child-inert guard. A SIBLING of the SHIPPED_TOOLS comparison above, not a
  # nested branch: the two checks read independent inputs, so a missing tool
  # name must not suppress the guard result. The bridge sets CHILD_INERT_MARKER
  # in the parent's environment before dispatching, so the child's copy of the
  # generated Trellis extension returns at load instead of running the PARENT's
  # per-turn session path. That guard lives in a generated file this repo cannot
  # edit, so a `trellis update` that renames the variable or moves the guard
  # below the registration calls would silently restore the wrong breadcrumb in
  # every dispatched child. Presence alone is not enough: a guard after the
  # registration calls registers everything and then returns.
  #
  # The `$ext_names` guard is load-bearing. With no dispatch tool registered, the
  # generated extension has no registration call to compare a guard against, and
  # SHIPPED_TOOLS deliberately `warn`s rather than fails for that shape — so a
  # bare dedent would have the two sibling checks contradict each other. When the
  # tree registers nothing, this check has no input and stays quiet.
  #
  # `pi.registerTool?.(` is the call form; the bare word `registerTool` is the
  # type annotation above the guard, and `pi.registerTool(` matches nothing.
  #
  # The guard scan admits only statement-shaped lines: line comments and
  # block-comment lines are dropped, the line must open with the `if` keyword and
  # a `(`, and it must carry the word `return`. Without that, deleting the real
  # guard and leaving a comment which merely mentions the marker and the word
  # `return` above the registration makes this check report `ok` with exit 0 —
  # measured with a `//` line naming the marker, with a `/* … */` line saying it
  # "shifts the child; returns early", and with a bare `<marker>: if (set) handlers
  # return early` line. The first needs the `//` filter, the second the
  # block-comment filter, and the third is why each pattern is anchored on the
  # `grep -n` prefix — a bare `: *if` also matches a colon INSIDE the text. A
  # false `bad` is the acceptable direction (see shell-guidelines.md on filtering
  # a scanner's own output): a reflowed comment costs a reworded line, while a
  # filter loose enough to accept a comment as a guard is unrecoverable. R4's
  # tolerance is unaffected — spacing, quote style, `== "1"`, `if(…)return;`,
  # `{ return; }`, and a trailing block comment after a real guard all still pass.
  if [ -n "$ext_names" ]; then
    marker="$(grep 'CHILD_INERT_MARKER' "$bridge_src" 2>/dev/null | grep -v '//' | head -n 1 |
      grep -oE '"[A-Z_]+"' | tr -d '"')"
    if [ -z "$marker" ]; then
      bad "read no marker name from the CHILD_INERT_MARKER declaration in $bridge_file (empty or reformatted?); the child-inert guard cannot be verified"
    else
      guard_line="$(grep -nF "$marker" "$trellis_ext" 2>/dev/null | grep -v '//' |
        grep -vE '^[0-9]+:[[:space:]]*(/\*|\*)' | grep -E '^[0-9]+:[[:space:]]*if[[:space:]]*\(' | grep -E '\breturn\b' |
        head -n 1 | cut -d: -f1)"
      reg_line="$(grep -n 'pi\.registerTool' "$trellis_ext" 2>/dev/null | head -n 1 | cut -d: -f1)"
      if [ -z "$guard_line" ]; then
        bad "the child-inert guard is gone: the generated extension no longer returns early on $marker, so a dispatched child runs the parent's per-turn session path"
      elif [ -z "$reg_line" ]; then
        bad "the child-inert guard cannot be positioned: no registration call was found in .pi/extensions/trellis/index.ts to compare $marker against"
      elif [ "$guard_line" -ge "$reg_line" ]; then
        bad "the child-inert guard is no longer first: $marker at line $guard_line is not before the first registration at line $reg_line"
      else
        ok "child-inert guard precedes registration ($marker at line $guard_line, registration at $reg_line)"
      fi
    fi
  fi

  # A role marker the bridge's predicates read must have a line that ASSIGNS it.
  #
  # Measured 2026-09-15: BRIDGE_CHILD_MARKER was read by isBridgeChild() and
  # isOtherChild() and assigned nowhere, so isOtherChild() was true in every
  # child, the child branch returned at extension load, and every dispatched
  # child silently received no context at all — no curated manifest, no task
  # artifacts, and no breadcrumb either. doctor.sh was green throughout: the
  # extension loaded, the child reported no_task, and nothing looked at the
  # constant. `grep -c 'process.env[BRIDGE_CHILD_MARKER] = '` returning 0 was the
  # whole bug. The delivery probe found it; reading the diff did not.
  #
  # Scope is the bridge's OWN markers only. A name it inherits or observes
  # (PI_SUBAGENT_CHILD, TRELLIS_CONTEXT_ID) is read-only here by design and is
  # not this file's to set, so demanding an assignment for it would be wrong.
  # The extraction therefore takes whole `const` identifiers and filters by
  # suffix, rather than matching a suffix and truncating the name: a truncated
  # name would produce a false `bad` for a marker that is correctly assigned.
  #
  # This is a floor, not a ceiling, and the label says so: it proves an
  # assignment exists somewhere in the file, not that it sits in the right place
  # or is gated on a resolved task. Those need reading.
  bridge_markers="$(grep -oE '^const [A-Z_]+ ' "$bridge_src" 2>/dev/null | awk '{print $2}' |
    grep -E '_(MARKER|ENV)$' | sort -u)"
  if [ -z "$bridge_markers" ]; then
    bad "read no role marker declaration from $bridge_file (empty or reformatted?); the markers its predicates read cannot be verified"
  else
    unassigned_markers=()
    while IFS= read -r m; do
      [ -n "$m" ] || continue
      grep -qF "process.env[$m] = " "$bridge_src" 2>/dev/null || unassigned_markers+=("$m")
    done <<<"$bridge_markers"
    if [ ${#unassigned_markers[@]} -gt 0 ]; then
      bad "bridge marker(s) read but never assigned: ${unassigned_markers[*]}"
      printf '      a marker the role predicates read must be set somewhere in %s\n' "$bridge_file"
      printf '      measured 2026-09-15: this is how every dispatched child silently lost its context\n'
    else
      n_markers="$(printf '%s\n' "$bridge_markers" | grep -c .)"
      ok "bridge role marker(s) assigned ($n_markers: $(printf '%s\n' "$bridge_markers" | tr '\n' ' '))"
    fi
  fi
fi

# Footer ownership. Line 2 of the footer belongs to Pi core. An extension that
# replaces the footer with `ctx.ui.setFooter()` takes the whole line and silently
# deletes whatever core added there — that is how `npm:pi-timer` dropped core's
# `CH<rate>%` segment and its `(sub)` subscription case. Statuses compose
# (`ctx.ui.setStatus()`); footers do not.
#
# Only a CALL is a violation, so a `//` comment line is not an offender: this is
# the one rule whose explanation is necessarily written in the files it governs.
# Every "cannot see" path below is a `bad`, following the shipped-tool check —
# a check that reports `ok` after it has stopped reading is worse than no check.
echo "==> Footer ownership"
ext_sources=()
# Recursive, because an extension may grow a second file. A shallower glob would
# report `ok` for a source it never read, which is the failure this section exists
# to prevent. node_modules is excluded: a vendored tree is not our source.
while IFS= read -r f; do
  if [ -n "$f" ]; then ext_sources+=("$f"); fi
done < <(find "$REPO_DIR/pi-agent/extensions" -type f -name '*.ts' \
  -not -path '*/node_modules/*' 2>/dev/null | sort)
if [ ${#ext_sources[@]} -eq 0 ]; then
  bad "no extension source found under pi-agent/extensions/; footer ownership cannot be verified"
else
  # Absolute paths, because doctor.sh is runnable from any cwd. Only the printed
  # form is relative to the repo.
  footer_hits="$(grep -Hn 'setFooter' "${ext_sources[@]}" 2>/dev/null)"
  scan_status=$?
  footer_offenders="$(printf '%s\n' "$footer_hits" | grep -vE ':[0-9]+:[[:space:]]*//' | sed "s|^$REPO_DIR/||")"
  if [ "$scan_status" -gt 1 ]; then
    bad "grep could not read every extension source; footer ownership is unverified"
  elif [ -n "$footer_offenders" ]; then
    bad "extension(s) call ctx.ui.setFooter(), replacing Pi core's footer:"
    printf '%s\n' "$footer_offenders" | while IFS= read -r line; do printf '      %s\n' "$line"; done
    printf '      line 2 belongs to Pi core; publish through ctx.ui.setStatus() instead\n'
  else
    ok "no setFooter() call in ${#ext_sources[@]} extension file(s)"
  fi
fi

echo "==> Credentials"
if [ -f "$PI_DST/auth.json" ]; then
  perms="$(stat -c '%a' "$PI_DST/auth.json" 2>/dev/null || stat -f '%Lp' "$PI_DST/auth.json")"
  if [ "$perms" = "600" ]; then
    ok "auth.json present, mode 600"
  else warn "auth.json mode is $perms (expected 600)"; fi
else
  warn "auth.json missing (run ./setup.sh, then add your keys)"
fi

echo "==> Secret scan (tracked files)"
if [ -d "$REPO_DIR/.git" ]; then
  hits="$(git -C "$REPO_DIR" grep -nEI \
    -e 'api[_-]?key"?[[:space:]]*[:=][[:space:]]*"[A-Za-z0-9_-]{16,}' \
    -e 'sk-[A-Za-z0-9]{20,}' \
    -e 'ghp_[A-Za-z0-9]{20,}' \
    -e 'Bearer [[:space:]]*[A-Za-z0-9._-]{20,}' \
    -- . 2>/dev/null | grep -v 'example' || true)"
  if [ -n "$hits" ]; then
    bad "possible secrets in tracked files:"
    printf '%s\n' "$hits" | sed 's/^/      /'
  else
    ok "no obvious secrets tracked"
  fi
  if git -C "$REPO_DIR" ls-files --error-unmatch pi-agent/auth.json >/dev/null 2>&1; then
    bad "pi-agent/auth.json is TRACKED by git — remove it from history"
  else
    ok "auth.json is not tracked"
  fi
fi

echo "==> Ignore coverage (machine-local paths)"
if [ -d "$REPO_DIR/.git" ]; then
  not_ignored=()
  for name in "${PI_NOT_SYNCED[@]}"; do
    git -C "$REPO_DIR" check-ignore -q -- "pi-agent/$name" || not_ignored+=("$name")
  done
  if [ ${#not_ignored[@]} -gt 0 ]; then
    bad "path(s) sync.sh reports as not-synced, but git would commit:"
    for name in "${not_ignored[@]}"; do printf '      pi-agent/%s\n' "$name"; done
    printf '      add them to .gitignore (directory patterns need the trailing slash)\n'
  else
    ok "all ${#PI_NOT_SYNCED[@]} reported-skipped paths are gitignored"
  fi
fi

echo "==> Skills  ($SKILLS_DST)"
if [ -f "$REPO_DIR/skills.json" ]; then
  total="$(node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).skills.length)' "$REPO_DIR/skills.json")"
  if node "$REPO_DIR/scripts/install-skills.mjs" "$REPO_DIR" --check >/tmp/pi-doctor-skills.$$ 2>&1; then
    ok "$total skill(s) installed from upstream"
  else
    bad "missing skills (run ./setup.sh):"
    sed 's/^/      /' /tmp/pi-doctor-skills.$$
  fi
  rm -f /tmp/pi-doctor-skills.$$
  prov="${SKILLS_DST%/skills}/.pi-setup-skills.json"
  if [ -f "$prov" ]; then
    node -e '
      const p=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"));
      for (const [id,s] of Object.entries(p.sources||{})) console.log(`  \u00b7 ${id} @ ${String(s.commit).slice(0,12)}`);
    ' "$prov"
  fi
else
  warn "no skills.json in repo"
fi

echo "==> Docs coverage (docs/ against what ships)"
if ! command -v node >/dev/null 2>&1; then
  # bad, not warn: this check is the only thing keeping a tracked document from
  # silently rotting, so a check that cannot run must fail. node is already a hard
  # dependency of the sections above.
  bad "node unavailable, cannot check docs/ coverage"
elif [ ! -d "$REPO_DIR/docs" ]; then
  bad "docs/ is missing"
elif node "$REPO_DIR/scripts/check-docs.mjs" "$REPO_DIR" >/tmp/pi-doctor-docs.$$ 2>&1; then
  ok "$(sed 's/^ *ok *//' /tmp/pi-doctor-docs.$$)"
else
  bad "docs/ coverage does not match the shipped set:"
  sed 's/^/      /' /tmp/pi-doctor-docs.$$
fi
rm -f /tmp/pi-doctor-docs.$$

echo
if [ "$problems" -eq 0 ] && [ "$notes" -eq 0 ]; then
  printf '\033[32mAll good.\033[0m\n'
elif [ "$problems" -eq 0 ]; then
  printf '\033[32mNo problems.\033[0m %d note(s) above.\n' "$notes"
else
  printf '\033[31m%d problem(s) found.\033[0m\n' "$problems"
  exit 1
fi
